#!/usr/bin/env bash
# Regenerates install.sh from the files in server/.
# Run after changing anything in server/, then commit both.
#
# install.sh carries the server files as a compressed bundle so one paste
# into the Lightsail SSH window installs or updates everything. The bundle
# is exactly the contents of server/ (checked with sha256 on unpack).
set -euo pipefail
cd "$(dirname "$0")/.."

files=(docker-compose.yml Caddyfile setup.sh users.sh rdio-admin.py users-admin/app.py alias-learner/app.py)
bundle=$(tar -C server --owner=0 --group=0 --mtime='2026-01-01' --sort=name \
	-cf - "${files[@]}" | xz -9e | base64 -w 76)
sums=$(cd server && sha256sum "${files[@]}")

out=install.sh
cat >"$out" <<EOF
#!/bin/sh
# Wake Radio installer / updater
# GENERATED by tools/build-install.sh from server/ in github.com/jbzambon/wakeradio.
#
# In the Lightsail SSH window:
#   cat > install.sh        (paste this whole file, Enter, then Ctrl+D)
#   sudo sh install.sh
#   sudo /opt/wakeradio/setup.sh
#
# Installs Docker if needed and unpacks the server files (the bundle below
# is server/ from the repo) into /opt/wakeradio. Safe to re-run to update:
# it never touches .env, the allowlist, logs or recorded calls. No secrets.
# Plain POSIX sh so it also works as a Lightsail launch script, size permitting.
set -eux
# Log to a file when run by Lightsail; show output when run by hand.
[ -t 1 ] || exec >>/var/log/wakeradio-launch.log 2>&1

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y docker.io docker-compose-v2 python3 curl unattended-upgrades
systemctl enable --now docker
usermod -aG docker ubuntu || true

# 1 GB swap so a small instance never runs out of memory during updates.
if [ ! -f /swapfile ]; then
  fallocate -l 1G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

mkdir -p /opt/wakeradio
cd /opt/wakeradio
base64 -d > /tmp/wakeradio.txz <<'BUNDLE'
\$bundle
BUNDLE
tar -xJf /tmp/wakeradio.txz --no-same-owner && rm -f /tmp/wakeradio.txz
sha256sum -c <<'SUMS'
\$sums
SUMS

chmod 755 setup.sh users.sh rdio-admin.py; chmod 644 users-admin/app.py alias-learner/app.py
ln -sf /opt/wakeradio/users.sh /usr/local/bin/wakeradio-users
docker compose pull -q || true   # warm the image cache; setup.sh starts everything
echo "Wake Radio files installed. Next: sudo /opt/wakeradio/setup.sh"
EOF
chmod +x "$out"
echo "wrote $out ($(wc -c <"$out") bytes)"
