#!/usr/bin/env bash
# Regenerates lightsail-launch-script.sh from the files in server/.
# Run after changing anything in server/, then commit both.
#
# The server files travel as a compressed bundle because Lightsail caps
# launch scripts at 16 KB. The bundle is exactly the contents of server/.
set -euo pipefail
cd "$(dirname "$0")/.."

files=(docker-compose.yml Caddyfile setup.sh users.sh rdio-admin.py)
bundle=$(tar -C server --owner=0 --group=0 --mtime='2026-01-01' --sort=name \
	-czf - "${files[@]}" | base64 -w 76)
sums=$(cd server && sha256sum "${files[@]}")

out=lightsail-launch-script.sh
cat >"$out" <<EOF
#!/bin/bash
# Wake Radio - Lightsail launch script
# GENERATED by tools/build-launch-script.sh from server/ in github.com/jbzambon/wakeradio.
#
# Paste this whole file into Lightsail > Create instance > "Add launch script".
# It installs Docker and unpacks the server files (the bundle below is just
# server/ from the repo, compressed to fit Lightsail's 16 KB limit) into
# /opt/wakeradio. It holds no secrets. When the instance is running, click
# "Connect using SSH" and run:   sudo /opt/wakeradio/setup.sh
set -euxo pipefail
exec > >(tee -a /var/log/wakeradio-launch.log) 2>&1

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y docker.io docker-compose-v2 python3 curl unattended-upgrades
systemctl enable --now docker
usermod -aG docker ubuntu || true

# 1 GB swap so a small instance never runs out of memory during updates.
if [ ! -f /swapfile ]; then
  fallocate -l 1G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

mkdir -p /opt/wakeradio
cd /opt/wakeradio
base64 -d > /tmp/wakeradio.tgz <<'BUNDLE'
$bundle
BUNDLE
tar -xzf /tmp/wakeradio.tgz --no-same-owner && rm -f /tmp/wakeradio.tgz
sha256sum -c <<'SUMS'
$sums
SUMS

chmod 755 setup.sh users.sh rdio-admin.py
ln -sf /opt/wakeradio/users.sh /usr/local/bin/wakeradio-users
docker compose pull -q || true   # warm the image cache; setup.sh starts everything
echo "Wake Radio files installed. Next: sudo /opt/wakeradio/setup.sh"
EOF
chmod +x "$out"
size=$(wc -c <"$out")
echo "wrote $out ($size bytes)"
[ "$size" -lt 16000 ] || { echo "too big for Lightsail (16 KB limit)" >&2; exit 1; }
